import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Learnify",
  description:
    "Interactive platform for learning with lessons, quizzes, and progress tracking.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "learnifyPlatform",
    "learn-language",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "learnify",
    "postgresql",
    "sonner",
    "drizzle",
    "zustand",
    "mysql",
    "lucide-react",
    "next-themes",
    "clerk-themes",
    "clerk",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
} as const;
